# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62c503c5579c0448635fa61277207d098943061f20464353966d316489c322cf98e538de9d4278e9392d66db1e34cd018099f120887f04dfb72b8b12b5f511f0

test:
  secret_key_base: 39410826d1d79fa825cada6cbff6d26671bf0279663d4e4aa156cd924e7fcf2a5d5d9503a37033a985ce0c1a6c1bac58cf75fd2c9d8cffc95bfc386a79ea50f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
